apiVersion: apps/v1
kind: Deployment
metadata:
  name: "uni-events-{{ .Values.environment }}-deployment"
  namespace: {{ .Values.environment }}
  labels:
    app: "uni-events-{{ .Values.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "uni-events-{{ .Values.environment }}"
  template:
    metadata:
      labels:
        app: "uni-events-{{ .Values.environment }}"
    spec:
      containers:
      - name: "uni-events"
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            requests:
              cpu: {{ default "100m" .Values.requests.cpu }}
              memory: {{ default "256Mi" .Values.requests.memory  }}
            limits:
              cpu: {{  default "500m" .Values.limits.cpu }}
              memory: {{ default "1024Mi" .Values.limits.memory }}
        volumeMounts:
        - name: secrets-uni-events
          mountPath: "/mnt/secrets-store"
          readOnly: true

        env:
        - name: BATCH_SIZE
          valueFrom:
            secretKeyRef:
              name: uni-events-batchsize
              key: batchsize
        - name: USER
          valueFrom:
            secretKeyRef:
              name: uni-events-user
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: uni-events-password
              key: password
        - name: SERVER
          valueFrom:
            secretKeyRef:
              name: uni-events-server
              key: server
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: uni-events-database
              value: database
        - name: SCHEMA
          valueFrom:
            secretKeyRef:
              name: uni-events-schema
              value: schema
        - name: GET_EVENTS_PROC
          valueFrom:
            secretKeyRef:
              name: uni-events-geteventsproc
              value: geteventsproc
        - name: MSDIFF
          valueFrom:
            secretKeyRef:
              name: uni-events-msdiff
              value: msdiff

      volumes:
        - name: secrets-uni-events
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-{{ .Values.keyVaultName }}-wi