apiVersion: apps/v1
kind: Deployment
metadata:
  name: "uni-events-{{ .Values.environment }}-deployment"
  namespace: {{ .Values.environment }}
  labels:
    app: "uni-events-{{ .Values.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "uni-events-{{ .Values.environment }}"
  template:
    metadata:
      labels:
        app: "uni-events-{{ .Values.environment }}"
    spec:
      containers:
      - name: "uni-events"
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            requests:
              cpu: {{ default "100m" .Values.requests.cpu }}
              memory: {{ default "256Mi" .Values.requests.memory  }}
            limits:
              cpu: {{  default "500m" .Values.limits.cpu }}
              memory: {{ default "1024Mi" .Values.limits.memory }}
        volumeMounts:
        - name: variables-env
          mountPath: /.env
          subPath: .env
      volumes:
      - name: variables-env
        configMap:
          name: 'uni-events-{{ .Values.environment }}-configmap'
          items:
          - key: .env
            path: .env