apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-{{ .Values.keyVaultName }}-wi
  namespace: {{ .Values.environment }}
spec:
  provider: azure
  secretObjects:
  - secretName: uni-events-batchsize
    type: Opaque
    data:
    - objectName: batchsize
      key: batchsize
  - secretName: uni-events-user
    type: Opaque
    data:
    - objectName: user
      key: user
  - secretName: uni-events-password
    type: Opaque
    data:
    - objectName: password
      key: password
  - secretName: uni-events-server
    type: Opaque
    data:
    - objectName: server
      key: server
  - secretName: uni-events-database
    type: Opaque
    data:
    - objectName: database
      key: database
  - secretName: uni-events-schema
    type: Opaque
    data:
    - objectName: schema
      key: schema
  - secretName: uni-events-geteventsproc
    type: Opaque
    data:
    - objectName: geteventsproc
      key: geteventsproc
  - secretName: uni-events-msdiff
    type: Opaque
    data:
    - objectName: msdiff
      key: msdiff
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.managedUserAssignedIdentityId }}
    keyvaultName: {{ .Values.keyVaultName }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: BATCH-SIZE
          objectType: secret
          objectAlias: batchsize
          objectVersion: ""
        - |
          objectName: USER
          objectType: secret
          objectAlias: user
          objectVersion: ""
        - |
          objectName: PASSWORD
          objectType: secret
          objectAlias: password
          objectVersion: ""
        - |
          objectName: SERVER
          objectType: secret
          objectAlias: server
          objectVersion: ""
        - |
          objectName: DATABASE
          objectType: secret
          objectAlias: database
          objectVersion: ""
        - |
          objectName: SCHEMA
          objectType: secret
          objectAlias: schema
          objectVersion: ""
        - |
          objectName: GET-EVENTS-PROC
          objectType: secret
          objectAlias: geteventsproc
          objectVersion: ""
        - |
          objectName: MSDIFF
          objectType: secret
          objectAlias: msdiff
          objectVersion: ""
    tenantId: {{ .Values.identityTenant }}