apiVersion: v1
kind: Service
metadata:
  name: "uni-events-{{ .Values.environment }}-service"
  namespace: {{ .Values.environment }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: "uni-events-{{ .Values.environment }}"
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer