kind: Secret
apiVersion: v1
metadata:
  name: application-core-services-{{ .Values.env }}-secret
  namespace: {{ .Values.env }}
data:
  variables.env: |
  {{- range $line := .Files.Get "variables.env" | split "\n" }}
  {{ $line | indent 2}}
  {{- end}}