kind: ConfigMap
apiVersion: v1
metadata:
  name: application-core-services-{{ .Values.env }}-configmap
  namespace: {{ .Values.env }}
  annotations:
    timestamp: "{{ now | date "20060102150405" }}"
data:
  variables.env: |
  {{- range $line := .Files.Get "variables.env" | split "\n" }}
  {{ $line | indent 2}}
  {{- end}}