changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bugfixes 🐞
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - "*"
