env: us-stress
loadBalancerIP: 172.172.61.65
image:
  port: 3333
  name: trkuniusstressacr.azurecr.io/us-stress/ann-sb-alert-sender # acr image name
replicaCount: 1

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: