apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "spsf-external-apis-{{ .Values.env }}-secrets-store"
  namespace: {{ .Values.env }}
spec:
  provider: azure
  secretObjects:
  - secretName: cosmosdbname
    type: Opaque
    data:
    - objectName: cosmosdbname
      key: cosmosdbname
  - secretName: cosmosdbendpoint
    type: Opaque
    data:
    - objectName: cosmosdbendpoint
      key: cosmosdbendpoint
  - secretName: cosmosdbkey
    type: Opaque
    data:
    - objectName: cosmosdbkey
      key: cosmosdbkey
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.secrets.kv_client_id }} 
    keyvaultName: {{ .Values.secrets.kv_name }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-name
          objectAlias: cosmosdbname
          objectType: secret
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-endpoint
          objectType: secret
          objectAlias: cosmosbdbendpoint
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-key
          objectType: secret
          objectAlias: cosmosdbkey
    tenantId: "a92ebf37-cae1-460d-8a16-ce7d28d0ff9c"