apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "spsf-external-apis-{{ .Values.env }}-secrets-store"
  namespace: {{ .Values.env }}
spec:
  provider: azure
  secretObjects:
  - secretName: cosmos_db_name
    type: Opaque
    data:
    - objectName: cosmos_db_name
      key: cosmos_db_name
  - secretName: cosmos_db_endpoint
    type: Opaque
    data:
    - objectName: cosmos_db_endpoint
      key: cosmos_db_endpoint
  - secretName: cosmos_db_key
    type: Opaque
    data:
    - objectName: cosmos_db_key
      key: cosmos_db_key
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.secrets.kv_client_id }} 
    keyvaultName: {{ .Values.secrets.kv_name }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-name
          objectAlias: cosmos_db_name
          objectType: secret
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-endpoint
          objectType: secret
          objectAlias: cosmosb_db_endpoint
        - |
          objectName: eapis-{{ .Values.env }}-azure-cosmos-db-key
          objectType: secret
          objectAlias: cosmos_db_key
    tenantId: "a92ebf37-cae1-460d-8a16-ce7d28d0ff9c"