apiVersion: v1
kind: Service
metadata:
  name: "spsf-external-apis-{{ .Values.env }}-service"
  namespace: {{ .Values.env }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: "spsf-external-apis-{{ .Values.env }}"
  ports:
  - protocol: TCP
    port: {{ .Values.image.port }}
    targetPort: {{ .Values.image.port }}
  type: LoadBalancer