appName: external
environment: stage
replicaCount: 1
loadBalancerIP: 172.190.141.199
image:
  name: multitenantacr.azurecr.io/external
  tag: "latest"
  port: 9000

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: