appName: filter
environment: stage
replicaCount: 5
loadBalancerIP: 74.235.253.39
image:
  name: multitenantacr.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu: 200m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi