appName: health-dash
environment: stage
replicaCount: 1
loadBalancerIP: 172.190.142.12
image:
  name: multitenantacr.azurecr.io/health-dash
  tag: "latest"
  port: 9111

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: