appName: mobile
environment: stage
replicaCount: 1
loadBalancerIP: 172.190.142.109
image:
  name: multitenantacr.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: