apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-{{ .Values.environment }}-service"
  namespace: {{ .Values.environment }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: "{{ .Values.appName}}-{{ .Values.environment }}"
  ports:
  - protocol: TCP
    port: {{ .Values.image.port }}
    targetPort: {{ .Values.image.port }}
  type: LoadBalancer