env: ppe
image:
  name: trkuniusstressacr.azurecr.io/ppe/ann-message-service
  tag: latest

loadBalancerIP: 172.206.98.131
sms:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

email:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: