env: us-stress
image:
  name:  trkuniusstressacr.azurecr.io/us-stress/ann-message-service
  tag: latest

sms:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

email:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: