kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: azure-disk
    namespace: ${{ .Values.env }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
