kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-{{ .Values.env }}
  namespace: {{ .Values.env }}
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi