appName: filter
environment: us-stress
replicaCount: 5
loadBalancerIP: 172.177.35.171
image:
  name: trkuniusstressacr.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu: 100m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi
