appName: mobile
environment: us-stress
replicaCount: 5
loadBalancerIP: 172.177.35.171
image:
  name: trkuniusstressacr.azurecr.io/us-stress/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: