appName: mobile
environment: us-stress
replicaCount: 5
loadBalancerIP: 172.177.36.135
image:
  name: trkuniusstressacr.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: