environment: dev
loadBalancerIP: 20.114.179.17
replicaCount: 1
image:
  name: trkuniusstressacr.azurecr.io/dev/uni-events
requests:
  cpu: 100m
  memory: 256Mi
limits:
  cpu: 500m
  memory: 1024Mi