env: test
loadBalancerIP: 172.200.153.255
image:
  port: 7000
  targetPort: 8080
  name: acrspsfstage.azurecr.io/dev/ann-rule-engine # acr image name
replicaCount: 1
requests:
  cpu:
  memory:

limits:
  cpu:
  memory: