appName: filter
environment: can-test
replicaCount: 20
loadBalancerIP: 20.12.83.241
image:
  name: trkuniusstressacr.azurecr.io/can-test/filter
  tag: "latest"
  port: 8098

requests:
  cpu: 200m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi
