appName: tapeevents
environment: can-test
replicaCount: 1
loadBalancerIP: 20.12.83.241
image:
  name: trkuniusstressacr.azurecr.io/can-test/tapeevents
  tag: "latest"
  port: 9002

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: