env: test
loadBalancerIP: 172.200.153.255
image:
  port: 3333
  name: acrspsfstage.azurecr.io/dev/ann-sb-alert-sender # acr image name
replicaCount: 1

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: