appName: health-dash
environment: dev
replicaCount: 1
loadBalancerIP: 172.171.217.29
image:
  name: multitenantacrdev.azurecr.io/health-dash
  tag: "latest"
  port: 9111

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: