appName: mobile
environment: dev
replicaCount: 1
loadBalancerIP: 172.171.217.29
image:
  name: multitenantacrdev.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: