appName: util
environment: dev
replicaCount: 1
loadBalancerIP: 13.92.31.102
image:
  name: multitenantacrdev.azurecr.io/util
  tag: "latest"
  port: 8191

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: