apiVersion: v1
kind: ConfigMap
metadata:
  name: spsf-cosmodbtocsv-backend-{{ .Values.env }}-configmap
  namespace: {{ .Values.env }}
data:
  .env: |
  {{- range $line := .Files.Get "variables.env" | split "\n" }}
  {{ $line | indent 2}}
  {{- end}}