apiVersion: v1
kind: Service
metadata:
  name: "spsf-cosmodbtocsv-frontend-{{ .Values.env }}-service"
  namespace: {{ .Values.env }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: "spsf-cosmodbtocsv-frontend-{{ .Values.env }}"
  ports:
  - protocol: TCP
    port: {{ .Values.image.port.frontend }}
    targetPort: {{ .Values.image.port.frontend }}
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: "spsf-cosmodbtocsv-backend-{{ .Values.env }}-service"
  namespace: {{ .Values.env }}
spec:
  selector:
    app: "spsf-cosmodbtocsv-backend-{{ .Values.env }}"
  ports:
  - protocol: TCP
    port: {{ .Values.image.port.backend }}
    targetPort: {{ .Values.image.port.backend }}
  type: LoadBalancer