appName: auth0
environment: qa
replicaCount: 1
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/auth0
  tag: "latest"
  port: 9005

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: