appName: health-dash
environment: qa
replicaCount: 1
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/health-dash
  tag: "latest"
  port: 9111

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: