appName: mobile
environment: qa
replicaCount: 1
loadBalancerIP: 20.115.122.222
image:
  name: multitenantdev2.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: