appName: tapeevents
environment: qa
replicaCount: 1
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/tapeevents
  tag: "latest"
  port: 9002

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: