appName: util
environment: qa
replicaCount: 1
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/util
  tag: "latest"
  port: 8191

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: