env: stage
loadBalancerIP: 172.203.47.236
image:
  port: 8080
  targetPort: 8080
  name: trkuniusstressacr.azurecr.io/stage/ann-rule-engine # acr image name
replicaCount: 1
requests:
  cpu:
  memory:

limits:
  cpu:
  memory: