appName: external
environment: prod
replicaCount: 1
loadBalancerIP: 23.96.24.227
image:
  name: multitenantacrprod.azurecr.io/external
  tag: "latest"
  port: 9000

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: