appName: filter
environment: prod
replicaCount: 5
loadBalancerIP: 23.96.24.227
image:
  name: multitenantacrprod.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu: 200m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi