appName: health-dash
environment: prod
replicaCount: 1
loadBalancerIP: 23.96.24.227
image:
  name: multitenantacrprod.azurecr.io/health-dash
  tag: "latest"
  port: 9111

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: