appName: mobile
environment: prod
replicaCount: 1
loadBalancerIP: 168.62.42.7
image:
  name: multitenantacrprod.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: