{{- if eq .Values.hpa.enabled true }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "spsf-core-{{ .Values.env }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "spsf-core-{{ .Values.env }}"
  minReplicas: {{ .Values.minReplicas | default 10 }}
  maxReplicas: {{ .Values.maxReplicas | default 20 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
{{- end }}
