env: test
image:
  name: repo/env/ann-message-service
  tag: latest
  port:
    sms: 9000
    email: 9001

loadBalancerIP: 127.0.0.1

sms:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

email:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: