appName: external
environment: manufacturing
replicaCount: 1
loadBalancerIP: 74.235.59.249
image:
  name: multitenantacrprod.azurecr.io/external
  tag: "latest"
  port: 9000

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: