appName: external
environment: manufacturing
replicaCount: 1
loadBalancerIP: 172.190.246.139
image:
  name: multitenantacrprod.azurecr.io/external
  tag: "latest"
  port: 9000

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: