appName: filter
environment: manufacturing
replicaCount: 5
loadBalancerIP: 74.235.59.249
image:
  name: multitenantacrprod.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: