apiVersion: v1
kind: Service
metadata:
  name: "ann-message-service-alerts-{{ .Values.env }}-service"
  namespace: {{ .Values.env }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.loadBalancerIP }}
spec:
  selector:
    app: "ann-message-service-alerts-{{ .Values.env }}"
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer