apiVersion: v1
kind: ConfigMap
metadata:
  name: ann-message-service-email-{{ .Values.env }}-configmap
  namespace: {{ .Values.env }}
data:
  .env: |
  {{- range $line := .Files.Get "email.env" | split "\n" }}
  {{ $line | indent 2}}
  {{- end}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ann-message-service-sms-{{ .Values.env }}-configmap
  namespace: {{ .Values.env }}
data:
  .env: |
  {{- range $line := .Files.Get "sms.env" | split "\n" }}
  {{ $line | indent 2}}
  {{- end}}