appName: mobile
environment: dev2
replicaCount: 5
loadBalancerIP: 20.228.253.144
image:
  name: multitenantdev2.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: