name: Plan Node dev
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      TFBACKEND:
        required: true
      TFSECRETVARS:
        required: true
env:
  TFVARS: ${{ vars.TFVARS }}
jobs:
  plan_scaleset:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Plan Scaleset
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Move terraform folder
      run: mkdir -p /tmp/terraform && cp -Rv terraform/* /tmp/terraform
    - name: Inject secrets
      env:
        TFBACKEND: '${{ secrets.TFBACKEND }}'
        TFSECRETVARS: '${{ secrets.TFSECRETVARS }}'
        WORK_DIR: /tmp/terraform
      run: |
        echo "$TFBACKEND" > $WORK_DIR/node-dev/backends/backend.conf
        echo "$TFSECRETVARS" > $WORK_DIR/node-dev/.auto.tfvars
        echo "$TFVARS" > $WORK_DIR/node-dev/terraform.tfvars
    - name: Setup terraform
      env:
        WORK_DIR: /tmp/terraform/node-dev
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Terraform Init
      env:
        WORK_DIR: /tmp/terraform/node-dev
      id: init
      run: cd $WORK_DIR && terraform init --backend-config=$WORK_DIR/backends/backend.conf

    - name: Terraform Validate
      env:
        WORK_DIR: /tmp/terraform/node-dev
      id: validate
      run: cd $WORK_DIR && terraform validate -no-color

    - name: Terraform Plan
      env:
        WORK_DIR: /tmp/terraform/node-dev
      id: plan
      run: cd $WORK_DIR && terraform plan -no-color
      continue-on-error: true
    - name: Clean terraform directory
      run: rm -r /tmp/terraform
    - name: Fail pipeline
      if: steps.plan.outcome != 'success'
      run: |
        echo "Terraform plan failed. Please, review logs"
        exit 1